version: 0.2


phases:
  install:
    commands:
      - echo Entered the install phase...
      - ls -l
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo docker hub login
      - docker login -u $LOGIN -p $PASSWD
      - echo docker login ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $DOCKER_URL
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - cat index.html
      - docker build -t $REPO_URL:init .
      - docker push $REPO_URL:init 
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
