version: 0.2


phases:
  install:
    commands:
      - echo Entered the install phase...
      - ls -l
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo docker hub login
      - docker login -u $LOGIN -p $PASSWD
      - echo docker login ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $DOCKER_URL
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:_latest}
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - cat index.html
      - docker build -t $REPO_URL:$IMAGE_TAG .
      - docker tag $REPO_URL:$IMAGE_TAG $REPO_URL:latest
      - docker push $REPO_URL:$IMAGE_TAG 
      - docker push $REPO_URL:latest
  post_build:
    commands:
      - echo Entered the post_build phase...
      - printf '[{"name":"web-app","imageUri":"%s"}]' $REPO_URL:${IMAGE_TAG}  > imagedefinitions.json
      - echo Build completed on `date`
artifacts:
    on-failure: CONTINUE
    files:
      - imagedefinitions.json
